name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
            npm i -g pnpm
            pnpm i

      - name: Build
        run: npm run build
        env:
          BASE_PATH: /opshala.github.io/

      - name: Create .nojekyll file
        run: touch .output/public/.nojekyll

      - name: Deploy pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: .output/public